#!/usr/bin/env bash
# installs nginx and configures to listen to port 80

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
service nginx start
