#!/usr/bin/env bash
# configure ufw to block all connections except http https ssh
sudo apt-get install ufw
sudo ufw disable
sudo ufw reset
sudo systemctl stop ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo systemctl start ufw
sudo ufw enable
sudo ufw status
